#server:
#  port: 8091
#  servlet:
#    context-path: /master
#
#spring:
#  application:
#    name: UserService
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/Jsw
#    username: postgres
#    password: 0367
#
#  jpa:
#    databasePlatform: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      ddlAuto: update
#    showSql: true
#
#
#
#
#
